# Basic `numpy` examples 

* from Chapter 3 of [Learning IPython for Interactive Computing and Data Visualization, second edition by Cyrille Rossant](https://www.packtpub.com/product/learning-ipython-for-interactive-computing-and-data-visualization-second-edition/9781783986989)
* more examples: https://github.com/ipython-books/minibook-2nd-code
* more advanced stuff: https://github.com/PacktPublishing/IPython-Interactive-Computing-and-Visualization-Cookbook-Second-Edition

In [1]:
import numpy as np

## Creating arrays

In [2]:
print("ones", np.ones(5))
print("arange", np.arange(5))
print("linspace", np.linspace(0., 1., 5))
print("random", np.random.uniform(size=3))
print("custom", np.array([2, 3, 5]))

ones [1. 1. 1. 1. 1.]
arange [0 1 2 3 4]
linspace [0.   0.25 0.5  0.75 1.  ]
random [0.53699456 0.13500697 0.74240717]
custom [2 3 5]


In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [5]:
np.arange(5).astype(np.float64)

array([0., 1., 2., 3., 4.])

## Slicing arrays

In [6]:
x = np.array([[1, 2], [3, 4]])
print(x.shape)
print(x)

(2, 2)
[[1 2]
 [3 4]]


In [7]:
# (0,0)th element
x[0,0]

1

In [8]:
# first row
x[0,:]

array([1, 2])

In [9]:
# second row
x[1,:]

array([3, 4])

In [10]:
# first column
x[:,0]

array([1, 3])

In [11]:
# second column
x[:,1]

array([2, 4])

## Basic array manipulations

In [12]:
x = np.arange(1, 11)
print(x.shape)
print(x)

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# to a row vector
x_row = x.reshape((1, -1))

print(x_row.shape)
print(x_row)

(1, 10)
[[ 1  2  3  4  5  6  7  8  9 10]]


In [14]:
# to a column vector
x_col = x.reshape((-1, 1))

print(x_col.shape)
print(x_col)

(10, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [15]:
# same thing can be done by addint a new 2nd dim
x_col = x[:, np.newaxis]

print(x_col.shape)
print(x_col)

(10, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


in `numpy` world `*` is the element-wise multiplication, not the matrix multiplicaiton!

In [16]:
x_row * x_row

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]])

In [17]:
# automatic broad casting! 
# (1x10) * (10x1) => (10,10) 
# Qhen one of the array's dimension is 1, it's "stretched" to match other array
x_row * x_col

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

For matrix multiplication, use `np.dot()`

In [18]:
# (1x10) * (10x1) => (1,1)
np.dot(x_row, x_col)

array([[385]])

In [19]:
# (10x1) * (1x10) => (10,10)
np.dot(x_col, x_row)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Mathematical operations on arrays

In [20]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [21]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [22]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])